apiVersion: v1
kind: Secret
metadata:
  name: {{ template "hyperf.fullname" . }}-env
  labels:
    app.kubernetes.io/name: {{ include "hyperf.fullname" . }}
    helm.sh/chart: {{ include "hyperf.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  ### <application> ###
  APP_NAME: {{ .Values.envs.app.name | b64enc | quote }}
  APP_ENV: {{ .Values.envs.app.env | b64enc | quote }}
  ### </application> ###

  ### <socketio> ###
  SOCKETIO_SERVER_URL: {{ .Values.envs.app.socketioServerUrl | b64enc | quote }}
  ### </socketio> ###

  ### <redis> ###
  REDIS_HOST: {{ .Values.envs.redis.host | b64enc | quote }}
  REDIS_AUTH: {{ .Values.envs.redis.auth | b64enc | quote }}
  REDIS_PORT: {{ .Values.envs.redis.port | b64enc | quote }}
  REDIS_DB: {{ .Values.envs.redis.db | b64enc | quote }}
  ### </redis> ###

  ### <db> ###
  DB_DRIVER: {{ .Values.envs.db.driver | b64enc | quote }}
  DB_HOST: {{ .Values.envs.db.host | b64enc | quote }}
  DB_PORT: {{ .Values.envs.db.port | b64enc | quote }}
  DB_DATABASE: {{ .Values.envs.db.database | b64enc | quote }}
  DB_USERNAME: {{ .Values.envs.db.username | b64enc | quote }}
  DB_PASSWORD: {{ .Values.envs.db.password | b64enc | quote }}
  DB_CHARSET: {{ .Values.envs.db.charset | b64enc | quote }}
  DB_COLLATION: {{ .Values.envs.db.collation | b64enc | quote }}
  DB_PREFIX: {{ .Values.envs.db.prefix | b64enc | quote }}
  ### </db> ###

  ### <auth> ###
  JWT_SECRET: {{ .Values.envs.auth.jwtSecret | b64enc | quote }}
  OAUTH_GITHUB_CLIENT_ID: {{ .Values.envs.auth.oauthGithubClientId | b64enc | quote }}
  OAUTH_GITHUB_CLIENT_SECRET: {{ .Values.envs.auth.oauthGithubClientSecret | b64enc | quote }}
  OAUTH_GOOGLE_CLIENT_ID: {{ .Values.envs.auth.oauthGoogleClientId | b64enc | quote }}
  OAUTH_GOOGLE_CLIENT_SECRET: {{ .Values.envs.auth.oauthGoogleClientSecret | b64enc | quote }}
  ### </auth> ###

  ### <youtube> ###
  YOUTUBE_DATA_API_KEY: {{ .Values.envs.youtube.dataApiKey | b64enc | quote }}
  ### </youtube> ###
