apiVersion: v1
kind: Service
metadata:
  name: {{ include "hyperf.fullname" . }}
  labels:
    name: {{ include "hyperf.fullname" . }}
    app.kubernetes.io/name: {{ include "hyperf.fullname" . }}
    helm.sh/chart: {{ include "hyperf.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: "{{ .Values.service.port }}"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.http }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.ports.ws }}
      targetPort: ws
      protocol: TCP
      name: ws
  selector:
    app: {{ include "hyperf.fullname" . }}
    app.kubernetes.io/name: {{ include "hyperf.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
