name: Analyse

on: push

jobs:
  run-phpstan:
    runs-on: ubuntu-latest
    name: PHPStan
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set branch name
        id: vars
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}
      - name: Set safe branch name
        env:
          SHORT_REF: ${{ steps.vars.outputs.short_ref }}
        id: safe_vars
        run: echo ::set-output name=short_ref::${SHORT_REF//\//\-}
      - name: Build
        run: docker build . -t ghcr.io/${{ github.repository }}:${{ steps.safe_vars.outputs.short_ref }} --build-arg WITH_DEV_DEPS=true
      - name: Run phpstan
        run: docker run --rm --entrypoint composer ghcr.io/${{ github.repository }}:${{ steps.safe_vars.outputs.short_ref }} analyse
  run-php-cs-fixer:
    runs-on: ubuntu-latest
    name: PHP-CS-Fixer
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set branch name
        id: vars
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}
      - name: Set safe branch name
        env:
          SHORT_REF: ${{ steps.vars.outputs.short_ref }}
        id: safe_vars
        run: echo ::set-output name=short_ref::${SHORT_REF//\//\-}
      - name: Build
        run: docker build . -t ghcr.io/${{ github.repository }}:${{ steps.safe_vars.outputs.short_ref }} --build-arg WITH_DEV_DEPS=true
      - name: Run php-cs-fixer
        run: docker run --rm --entrypoint composer ghcr.io/${{ github.repository }}:${{ steps.safe_vars.outputs.short_ref }} cs
