name: Release

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.ref }}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Copy kubeconfig
        env:
          KUBECONFIG_BASE64: ${{ secrets.KUBECONFIG_BASE64 }}
        run: mkdir -p ~/.kube && echo "$KUBECONFIG_BASE64" | base64 -d > ~/.kube/config
      - name: Copy helm values
        run: echo "$HELM_VALUES_BASE64" | base64 -d > .helm/values-production.yaml
        env:
          HELM_VALUES_BASE64: ${{ secrets.HELM_VALUES_BASE64 }}
      - name: Deploy
        run: |
          cd .helm
          helm dependency update
          helm upgrade -i --atomic -f values.yaml -f values-production.yaml collabatube .
